from setuptools import setup, find_packages

setup(
    name="rotrust",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "fastapi>=0.104.1",
        "uvicorn>=0.23.2",
        "pydantic>=2.4.2",
        "python-multipart>=0.0.6",
        "python-jose[cryptography]>=3.3.0",
        "passlib[bcrypt]>=1.7.4",
        "python-dotenv>=1.0.0",
        "httpx>=0.25.0",
        "sqlalchemy>=2.0.22",
        "alembic>=1.12.0",
        "psycopg2-binary>=2.9.9",
        "fabric-sdk-py>=0.9.0",
        "hyperledger-fabric-sdk>=0.8.0",
        "cryptography>=41.0.7",
        "PyJWT>=2.6.0",
    ],
    extras_require={
        "dev": [
            "pytest>=7.4.2",
            "pytest-asyncio>=0.21.1",
            "black>=23.9.1",
            "isort>=5.12.0",
            "flake8>=6.1.0",
            "mypy>=1.6.1",
        ],
    },
    author="RoTrust Team",
    author_email="contact@rotrust.ro",
    description="A blockchain-based platform for real estate transactions in Romania",
    keywords="blockchain, real estate, hyperledger fabric, fastapi",
    url="https://github.com/your-organization/rotrust",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
    python_requires=">=3.8",
)