name: Branch Protection

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  enforce-branch-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Check if push is direct to main
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.event.repository.default_branch == 'main'
        run: |
          echo "Direct pushes to main branch are not allowed!"
          echo "Please create a pull request instead."
          exit 1
          
      - name: Checkout code
        uses: actions/checkout@v3
        if: github.event_name == 'pull_request'
        
      - name: Validate pull request
        if: github.event_name == 'pull_request'
        run: |
          echo "Pull request to main branch detected."
          echo "This is the correct way to make changes to the main branch."
          echo "Please ensure your pull request has been reviewed before merging."