name: Branch Protection

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  enforce-branch-protection:
    runs-on: ubuntu-latest
    steps:
          
      - name: Checkout code
        uses: actions/checkout@v3
        if: github.event_name == 'pull_request'
        
      - name: Check for required approval
        if: github.event_name == 'pull_request'
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
          REQUIRED_APPROVER: "MarianStelianCraciun"  # Replace with the actual username
        run: |
          echo "Pull request to main branch detected."
          echo "Checking for required approval from $REQUIRED_APPROVER..."
          
          # Get the list of reviews for this PR
          REVIEWS=$(curl -s -H "Authorization: token $GH_TOKEN" \
            "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER/reviews")
          
          # Check if the required approver has approved the PR
          APPROVED=$(echo $REVIEWS | jq -r --arg APPROVER "$REQUIRED_APPROVER" '.[] | select(.user.login==$APPROVER and .state=="APPROVED") | .state')
          
          if [ "$APPROVED" == "APPROVED" ]; then
            echo "✅ Pull request has been approved by $REQUIRED_APPROVER."
            echo "This PR can be merged to the main branch."
          else
            echo "❌ Pull request has NOT been approved by $REQUIRED_APPROVER."
            echo "This PR cannot be merged until it receives approval from $REQUIRED_APPROVER."
            exit 1
          fi